### PR TITLE
Enable x86_64-darwin, aarch64-darwin nix builds

### PR DESCRIPTION
**Pull request by carbolymer**
# Changelog

```yaml
- description: |
    Enable x86_64-darwin, aarch64-darwin nix builds
# uncomment types applicable to the change:
  type:
  # - feature        # introduces a new feature
  # - breaking       # the API has changed in a breaking way
  # - compatible     # the API has changed but is non-breaking
  # - optimisation   # measurable performance improvements
  # - improvement    # QoL changes e.g. refactoring
  # - bugfix         # fixes a defect
  # - test           # fixes/modifies tests
   - maintenance    # not directly related to the code
  # - release        # related to a new release preparation
  # - documentation  # change in code docs, haddocks...
```

# Context

Additional context for the PR goes here. If the PR fixes a particular issue please provide a [link](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword=) to the issue.

# How to trust this PR

Highlight important bits of the PR that will make the review faster. If there are commands the reviewer can run to observe the new behavior, describe them.

# Checklist

- [ ] Commit sequence broadly makes sense and commits have useful messages
- [ ] New tests are added if needed and existing tests are updated. See [Running tests](https://github.com/input-output-hk/cardano-node-wiki/wiki/Running-tests) for more details
- [ ] Self-reviewed the diff

### CODE REVIEW

**Comment by angerman** [comment]
We don't have native aarch64-Linux builders. This will go through qemu on x86_64-linux and be *really* slow.

We can do x86_64-linux -> aarch64-linux cross though. 

I'd strongly suggest against asrch64-linux native. 

If we do consider this a necessity, we need to get a native arch64 machine.

**Review by angerman — APPROVED** [review]
LGTM

**Comment by carbolymer** [comment]
@angerman Thanks for the explanation and review! We're still evaluating if we need extra architectures built in CLI repo and is the extra build time worth it.

**Review by smelc — APPROVED** [review]

**Comment by angerman** [comment]
> @angerman Thanks for the explanation and review! We're still evaluating if we need extra architectures built in CLI repo and is the extra build time worth it.

Cross compiling to aarch64-Linux works quite well.

**Comment by smelc** [comment]
@carbolymer> any plan to merge this one soon? We definitely want this one merged before the next release of the CLI.

**Pull request merged**
