### PR TITLE
Rename create-new-committee into update-committee

### LINKED ISSUE #335: action create-new-committee needs amendment
`cardano-cli conway governance action create-new-committee` needs to be adjusted in concordance with https://github.com/input-output-hk/cardano-ledger/pull/3721 So we need 2 things: 

- [ ] Rename `create-new-committee` to `update-committee`  
~Make it be able to --remove-cc without forcing a replacement with an --add-cc as explained below~ Not an issue

### PR DESCRIPTION
**Pull request by smelc**
# Changelog

```yaml
- description: |
    Rename create-new-committee into update-committee
# uncomment types applicable to the change:
  type:
  # - feature        # introduces a new feature
  - breaking       # the API has changed in a breaking way
  # - compatible     # the API has changed but is non-breaking
  # - optimisation   # measurable performance improvements
  - improvement    # QoL changes e.g. refactoring
  # - bugfix         # fixes a defect
  # - test           # fixes/modifies tests
  # - maintenance    # not directly related to the code
  # - release        # related to a new release preparation
  # - documentation  # change in code docs, haddocks...
```

# Context

Fixes https://github.com/input-output-hk/cardano-cli/issues/335

# Checklist

- [X] Commit sequence broadly makes sense and commits have useful messages
- [X] The change log section in the PR description has been filled in
- [X] New tests are added if needed and existing tests are updated.  These may include:
  - golden tests
  - property tests
  - round trip tests
  - integration tests
  See [Running tests](https://github.com/input-output-hk/cardano-node-wiki/wiki/Running-tests) for more details
- NA The version bounds in `.cabal` files are updated
- [X] CI passes. See note on CI.  The following CI checks are required:
  - [X] Code is linted with `hlint`.  See `.github/workflows/check-hlint.yml` to get the `hlint` version
  - [X] Code is formatted with `stylish-haskell`.  See `.github/workflows/stylish-haskell.yml` to get the `stylish-haskell` version
  - [X] Code builds on Linux, MacOS and Windows for `ghc-8.10.7` and `ghc-9.2.7`
- [X] The changelog section in the PR is updated to describe the change
- [X] Self-reviewed the diff

### CODE REVIEW

**Comment by smelc** [comment]
cc @CarlosLopezDeLara

**Comment by CarlosLopezDeLara** [comment]
```
cardano-cli conway governance action update-committee \
--testnet \
--governance-action-deposit 0 \
--stake-verification-key-file example/utxo-keys/stake1.vkey \
--proposal-url https://shorturl.at/asIJ6 \
--proposal-file example/transactions/cc_proposal.txt \
--add-cc-cold-verification-key-file example/cc/cold1-cc.vkey \
--epoch 202 \
--add-cc-cold-verification-key-file example/cc/cold2-cc.vkey \
--epoch 252 \
--quorum 51/100 \
--out-file example/transactions/update-committee.action
```

```
cat example/transactions/new-committee.action
{
    "type": "Governance proposal",
    "description": "",
    "cborHex": "8400581de05fd2fa72549639d76d48569eec31e63a5692e58375b2c708f27b299a8504f680a28200581c03fb852259ba0feb3f71ec2f5a108c133599d6a652aaed03590bcce318fc8200581cf7f2a37830d35650a6132f6bb9752e1967c158e842e3bbd5ac7b2a4818cad81e821833186482781968747470733a2f2f73686f727475726c2e61742f6173494a3658203d2a9d15382c14f5ca260a2f5bfb645fe148bfe10c1d0e1d305b7b1393e2bd97"
}
```
```
[0, h'E05FD2FA72549639D76D48569EEC31E63A5692E58375B2C708F27B299A', [4, null, [], {[0, h'03FB852259BA0FEB3F71EC2F5A108C133599D6A652AAED03590BCCE3']: 252, [0, h'F7F2A37830D35650A6132F6BB9752E1967C158E842E3BBD5AC7B2A48']: 202}, 30([51, 100])], ["https://shorturl.at/asIJ6", h'3D2A9D15382C14F5CA260A2F5BFB645FE148BFE10C1D0E1D305B7B1393E2BD97']]
```

**Review by CarlosLopezDeLara — APPROVED** [review]

**Comment by smelc** [comment]
@CarlosLopezDeLara> what is the output `[0, h'E05FD2FA72549639D76D48569EEC31E63A5692E58375B2C708F27B299A', [4, null, [], {[0, h'03FB852259BA0FEB3F71EC2F5A108C133599D6A652AAED03590BCCE3']: 252, [0, h'F7F2A37830D35650A6132F6BB9752E1967C158E842E3BBD5AC7B2A48']: 202}, 30([51, 100])], ["https://shorturl.at/asIJ6", h'3D2A9D15382C14F5CA260A2F5BFB645FE148BFE10C1D0E1D305B7B1393E2BD97']]` in your previous comment?

How did you generate it?

**Comment by CarlosLopezDeLara** [comment]
@smelc 

I bring the bytes on the text envelope 840058...  to https://cbor.me/  and compare the result to the cddl 

https://github.com/input-output-hk/cardano-ledger/blob/master/eras/conway/test-suite/cddl-files/conway.cddl

**Pull request merged**
