### PR TITLE
Add one missing extended to non extended golden tests

### LINKED ISSUE #424: Add missing golden tests for extended->non-extended conversion
Are we missing golden tests if only two golden files have changed?

_Originally posted by @newhoggy in https://github.com/input-output-hk/cardano-cli/pull/416#discussion_r1378700192_
            
# How to tackle this issue

* Look at the golden tests changed by https://github.com/input-output-hk/cardano-cli/pull/416
* Identify the type of extended keys for which no tests was changed by https://github.com/input-output-hk/cardano-cli/pull/416
* Add tests for those extended keys

### PR DESCRIPTION
**Pull request by smelc**
# Changelog

```yaml
- description: |
    Add a test of extended to non-extended conversions, for a type of key that was untested
# uncomment types applicable to the change:
  type:
  # - feature        # introduces a new feature
  # - breaking       # the API has changed in a breaking way
  # - compatible     # the API has changed but is non-breaking
  # - optimisation   # measurable performance improvements
  # - improvement    # QoL changes e.g. refactoring
  # - bugfix         # fixes a defect
  - test           # fixes/modifies tests
  # - maintenance    # not directly related to the code
  # - release        # related to a new release preparation
  # - documentation  # change in code docs, haddocks...
```

# Context

Fixes https://github.com/input-output-hk/cardano-cli/issues/424

# How to trust this PR

Highlight important bits of the PR that will make the review faster. If there are commands the reviewer can run to observe the new behavior, describe them.

# Checklist

- [x] Commit sequence broadly makes sense and commits have useful messages
- [x] New tests are added if needed and existing tests are updated. See [Running tests](https://github.com/input-output-hk/cardano-node-wiki/wiki/Running-tests) for more details
- [x] Self-reviewed the diff

### CODE REVIEW

**Comment by smelc** [comment]
For the record, the input file `cardano-cli/test/cardano-cli-golden/files/input/key/non-extended-keys/extended-payment.vkey` was generated with:

```
cardano-signer keygen --json-extended --path 1852H/1815H/0H/0/0 --vkey-extended | jq
```

(thanks @gitmachtl for the tool :heart:)

**Comment by smelc** [comment]
@gitmachtl> could you tell me how to generate a _genesis delegate extended verification key_? I can't find out by myself.

**Comment by gitmachtl** [comment]
> @gitmachtl> could you tell me how to generate a _genesis delegate extended verification key_? I can't find out by myself.

you mean a `GenesisDelegateSigningKey_ed25519` in extended format?

these are just normal ed25519 keys, you can generate them like you did with the ones above via

``` console
cardano-signer keygen --path payment --vkey-extended --out-skey genesis-del.skey --out-vkey genesis-del.vkey
```

in extended format and simply rename the `type` and `description` in the output files. i have never seen a genesis or genesis-delegate key in extended format. not even sure if there is a proper `type` for it like `GenesisExtendedDelegateSigningKey_ed25519_bip32` ? i don't think there is a derivation path available for those keys tbh, so i would go with a regular payment one. outputformat is the same.

@disassembler do you know about derivation paths for genesis keys and genesis delegation keys?

**Comment by smelc** [comment]
>  you mean a GenesisDelegateSigningKey_ed25519 in extended format?

I'm not sure as I'm not familiar with the different variations of key. My interest comes from the presence of [AGenesisDelegateExtendedVerificationKey](https://github.com/input-output-hk/cardano-api/blob/8091a24f77478306ce7029a33f2c3f53c8c6e3b8/cardano-api/internal/Cardano/Api/DeserialiseAnyOf.hs#L243) in `cardano-api`, which wraps a [GenesisDelegateExtendedKey](https://github.com/input-output-hk/cardano-api/blob/8091a24f77478306ce7029a33f2c3f53c8c6e3b8/cardano-api/internal/Cardano/Api/Keys/Shelley.hs#L1149).

cc @Jimbo4350 who maybe knows?

**Comment by smelc** [comment]
There is still one kind of extended keys that is not tested, but better merge this PR that let it bitrot, hence marking it ready.

**Review by carbolymer — APPROVED** [review]

**Pull request merged**
