### PR TITLE
Bump cardano-ping

### PR DESCRIPTION
**Pull request by bolt12**
# Changelog

```yaml
- description: |
    Bump cardano-ping version
# uncomment types applicable to the change:
  type:
  # - feature        # introduces a new feature
  # - breaking       # the API has changed in a breaking way
  - compatible     # the API has changed but is non-breaking
  # - optimisation   # measurable performance improvements
  # - improvement    # QoL changes e.g. refactoring
  # - bugfix         # fixes a defect
  # - test           # fixes/modifies tests
  # - maintenance    # not directly related to the code
  # - release        # related to a new release preparation
  # - documentation  # change in code docs, haddocks...
```

# Context

`cardano-cli` contains a fix for 8.9.0 release

### CODE REVIEW

**Comment by bolt12** [comment]
corresponding chap PR: https://github.com/IntersectMBO/cardano-haskell-packages/pull/689

**Comment by smelc** [comment]
@bolt12> since you updated both CHaP and hackage, you need to update the flake's lock for both too, like this:

```shell
nix flake update CHaP
nix flake update haskellNix/hackage
```

If I'm not mistaken, the change to `flake.lock` misses the second command

**Comment by bolt12** [comment]
I updated CHaP's flake.lock entry. I don't think hackage is necessary but I'll update it

**Review by smelc — APPROVED** [review]

**Comment by smelc** [comment]
@bolt12> I let you merge when you see fit.

**Comment by bolt12** [comment]
I am not authorized to merge it, unfortunately. Feel free to do so!

**Pull request merged**
