### PR TITLE
Release 8.20.4

### PR DESCRIPTION
**Pull request by bolt12**
# Changelog

```yaml
- description: |
    Release 8.20.4
# uncomment types applicable to the change:
  type:
  # - feature        # introduces a new feature
  # - breaking       # the API has changed in a breaking way
  # - compatible     # the API has changed but is non-breaking
  # - optimisation   # measurable performance improvements
  # - improvement    # QoL changes e.g. refactoring
  # - bugfix         # fixes a defect
  # - test           # fixes/modifies tests
  # - maintenance    # not directly related to the code
  - release        # related to a new release preparation
  # - documentation  # change in code docs, haddocks...
```

# Context

For 8.9.1

### CODE REVIEW

**Review by bolt12 — COMMENTED** [review]
This can be just a revision on CHaP that bumps cardano-api

**Comment by bolt12** [comment]
CHaP PR: https://github.com/IntersectMBO/cardano-haskell-packages/pull/705

**Review by carbolymer — CHANGES_REQUESTED** [review]
My remarks from there: https://github.com/IntersectMBO/cardano-api/pull/487#issuecomment-2004359319 also apply here

**Comment by bolt12** [comment]
I am going to close this since I only made a revision for cardano-cli on CHaP that bumps cardano-api

**Pull request closed without merging**
